export default [
  '(    oz.) tomato sauce',
  '1% low-fat milk',
  'Anaheim chile',
  'Asian fish sauce',
  "Baba's Fish Curry Powder",
  'Bengali 5 Spice',
  'Biryani Masala',
  'Boston lettuce',
  "Bull's Eye Original Barbecue Sauce",
  'English cucumber',
  'Knorr® Rice Sides™ - Chicken flavor Broccoli',
  'Madras curry powder',
  'Massaman curry paste',
  'Mountain High Yoghurt',
  'Philadelphia Cream Cheese',
  'Ragu Sauce',
  'Season Salmon',
  'Tabasco Green Pepper Sauce',
  'Thai red curry paste',
  'agave nectar',
  'ajwain',
  'aleppo pepper',
  'all-purpose flour',
  'allspice',
  'allspice berries',
  'almond butter',
  'almond milk',
  'almonds',
  'amba',
  'amchur',
  'anardana',
  'anise',
  'annatto powder',
  'apple cider vinegar',
  'apples',
  'arctic char',
  'arrowroot flour',
  'arrowroot powder',
  'arugula',
  'asafoetida',
  'asafoetida powder',
  'asian eggplants',
  'asparagus',
  'avocado',
  'avocado oil',
  'baby corn',
  'baby kale',
  'baby potatoes',
  'baby spinach',
  'baby spinach leaves',
  'baking potatoes',
  'baking soda',
  'bamboo shoots',
  'baobab fruit powder',
  'barramundi',
  'base',
  'basmati',
  'basmati rice',
  'bay leaf',
  'bay leaves',
  'bean sauce',
  'beans',
  'beansprouts',
  'beef',
  'beef bouillon',
  'beef roast',
  'beef short ribs',
  'beef stock',
  'beef strips',
  'bell pepper',
  'beluga lentil',
  'bengal gram',
  'berries',
  'bhaji',
  'bhindi',
  'bird chile',
  'bird pepper',
  'biscuit dough',
  'black beans',
  'black cardamom pods',
  'black chickpeas',
  'black cumin seeds',
  'black gram',
  'black grapes',
  'black lentil',
  'black mustard seeds',
  'black olives',
  'black pepper',
  'black peppercorns',
  'black salt',
  'black-eyed peas',
  'blanched almonds',
  'blue-eye fish',
  'boiled eggs',
  'boiling potatoes',
  'boiling water',
  'bone in chicken thighs',
  'bone-in chicken',
  'bone-in chicken breast halves',
  'boneless chicken',
  'boneless chicken breast',
  'boneless chicken thighs',
  'boneless mutton',
  'boneless pork shoulder',
  'boneless skinless chicken',
  'boneless skinless chicken breast halves',
  'boneless skinless chicken breasts',
  'boneless skinless chicken tenderloins',
  'boneless skinless chicken thighs',
  'bouillon',
  'broccoli',
  'broccoli florets',
  'brocolli florets',
  'broth',
  'brown basmati rice',
  'brown cardamom',
  'brown lentils',
  'brown mustard seeds',
  'brown rice',
  'brown rice pasta',
  'brown sugar',
  'brussels sprouts',
  'buns',
  'burger buns',
  'burger rolls',
  'butter',
  'butter beans',
  'buttermilk',
  'butternut squash',
  'button mushrooms',
  'cabbage',
  'cage free eggs',
  'candlenuts',
  'canned black beans',
  'canned chicken broth',
  'canned chickpeas',
  'canned chopped tomatoes',
  'canned tomatoes',
  'canola',
  'canola oil',
  'capsicum',
  'caraway seeds',
  'cardamom',
  'cardamom pods',
  'cardamom seeds',
  'cardamon',
  'carrots',
  'cashew nuts',
  'cashewnut powder',
  'cassia cinnamon',
  'catfish',
  'cauliflower',
  'cauliflower florets',
  'cayenne',
  'cayenne pepper',
  'cayenne pepper sauce',
  'celery',
  'celery ribs',
  'celery sticks',
  'chaat masala',
  'chana dal',
  'chard',
  'chat masala',
  'cherry tomatoes',
  'chestnut mushrooms',
  'chicken',
  'chicken bones',
  'chicken bouillon',
  'chicken breast halves',
  'chicken breasts',
  'chicken broth',
  'chicken cutlets',
  'chicken drumsticks',
  'chicken fillets',
  'chicken fingers',
  'chicken leg quarters',
  'chicken legs',
  'chicken pieces',
  'chicken stock',
  'chicken stock cubes',
  'chicken tenderloin',
  'chicken thigh fillets',
  'chicken thighs',
  'chicken wing drummettes',
  'chicken wings',
  'chickpea flour',
  'chickpeas',
  'chile de arbol',
  'chile pepper',
  'chile powder',
  'chiles',
  'chili',
  'chili flakes',
  'chili oil',
  'chili paste',
  'chili pepper',
  'chili powder',
  'chili sauce',
  'chilli paste',
  'chillies',
  'chinese eggplants',
  'chinese five-spice powder',
  'chipotle chile powder',
  'chole',
  'chopped almonds',
  'chopped cilantro',
  'chopped coriander',
  'chopped fresh cilantro',
  'chopped fresh mint',
  'chopped garlic',
  'chopped onion',
  'chopped parsley',
  'chopped potatoes',
  'chopped tomatoes',
  'chuck',
  'chutney',
  'cider vinegar',
  'cilantro',
  'cilantro leaves',
  'cilantro stems',
  'cinnamon',
  'cinnamon sticks',
  'clams',
  'clarified butter',
  'clove',
  'coarse salt',
  'coarse sea salt',
  'coconut',
  'coconut cream',
  'coconut flour',
  'coconut milk',
  'coconut milk powder',
  'coconut oil',
  'coconut sugar',
  'coconut vinegar',
  'coffee',
  'cooked brown rice',
  'cooked chicken',
  'cooked chicken breasts',
  'cooked quinoa',
  'cooked rice',
  'cooked white rice',
  'cooking cream',
  'cooking oil',
  'cooking spray',
  'coriander',
  'coriander powder',
  'coriander seeds',
  'corn flour',
  'corn oil',
  'corn starch',
  'corn tortillas',
  'couscous',
  'crab',
  'cracked black pepper',
  'cream',
  'cream substitute',
  'crimini mushrooms',
  'crosswise',
  'crushed garlic',
  'crushed red pepper',
  'crushed red pepper flakes',
  'crushed tomatoes',
  'crème fraîche',
  'cubed potatoes',
  'cucumber',
  'cumin',
  'cumin seed',
  'curds',
  'curly kale',
  'currant',
  'curry',
  'curry leaf',
  'curry leaves',
  'curry paste',
  'curry powder',
  'curry sauce',
  'curry seasoning',
  'daal',
  'daikon',
  'dal',
  'dark brown sugar',
  'dark sesame oil',
  'deveined shrimp',
  'dhal',
  'diced bell pepper',
  'diced chicken',
  'diced green chilies',
  'diced onions',
  'diced potatoes',
  'diced red onions',
  'diced tomatoes',
  'diced tomatoes in juice',
  'dill',
  'double cream',
  'dried chickpeas',
  'dried chile',
  'dried currants',
  'dried kidney beans',
  'dried lentils',
  'dried mint',
  'dried red chile peppers',
  'dried rose hips',
  'dried split peas',
  'dried thyme',
  'dry bread crumbs',
  'dry coconut',
  'dry mustard',
  'dry white wine',
  'egg noodles',
  'eggplant',
  'eggs',
  'essence',
  'extra firm tofu',
  'extra large shrimp',
  'extra virgin coconut oil',
  'extra-virgin olive oil',
  'farro',
  'fat',
  'fat free greek yogurt',
  'fat free yogurt',
  'fennel',
  'fennel seeds',
  'fenugreek',
  'fenugreek leaves',
  'fenugreek seeds',
  'filtered water',
  'fine salt',
  'fine sea salt',
  'finely chopped fresh parsley',
  'finely chopped onion',
  'firm tofu',
  'fish',
  'fish fillets',
  'fish sauce',
  'fish steaks',
  'fish stock',
  'flaked coconut',
  'flank steak',
  'flatbread',
  'florets',
  'flour',
  'food colouring',
  'free-range chickens',
  'french fried onions',
  'fresh basil',
  'fresh chicken stock',
  'fresh chile',
  'fresh cilantro',
  'fresh coriander',
  'fresh curry leaves',
  'fresh dill',
  'fresh ginger',
  'fresh ginger root',
  'fresh green beans',
  'fresh green peas',
  'fresh lemon',
  'fresh lemon juice',
  'fresh lime',
  'fresh lime juice',
  'fresh mint',
  'fresh mozzarella',
  'fresh mushrooms',
  'fresh parsley',
  'fresh peas',
  'fresh spinach',
  'fresh spinach leaves',
  'fresh tomatoes',
  'fresh tuna steaks',
  'fresh turmeric',
  'freshly ground black pepper',
  'freshly ground pepper',
  'fresno chiles',
  'frozen chopped spinach',
  'frozen mango',
  'frozen peas',
  'frozen peas and carrots',
  'frozen spinach',
  'full fat coconut milk',
  'full-fat plain yogurt',
  'galangal',
  'garam masala',
  'garbanzo beans',
  'garlic',
  'garlic bulb',
  'garlic chili sauce',
  'garlic cloves',
  'garlic flakes',
  'garlic paste',
  'garlic powder',
  'garlic puree',
  'ghee',
  'ginger',
  'ginger garlic paste',
  'ginger paste',
  'ginger piece',
  'ginger purée',
  'ginger root',
  'ginger syrup',
  'gingerroot',
  'gluten',
  'gluten free vegetable broth',
  'goat',
  'goat cheese',
  'gold potatoes',
  'golden raisins',
  'gram flour',
  'granulated sugar',
  'grape tomatoes',
  'grapeseed oil',
  'grass-fed butter',
  'grated coconut',
  'grated nutmeg',
  'grating cheese',
  'gravy',
  'greek yogurt',
  'green beans',
  'green bell pepper',
  'green bell pepper, sliced',
  'green cardamom',
  'green cardamom pods',
  'green chile',
  'green chilies',
  'green grapes',
  'green lentil',
  'green onions',
  'green peas',
  'green pepper',
  'green tomatoes',
  'greens',
  'ground allspice',
  'ground almonds',
  'ground beef',
  'ground black pepper',
  'ground cardamom',
  'ground cayenne pepper',
  'ground chicken',
  'ground chicken breast',
  'ground chipotle chile pepper',
  'ground chuck',
  'ground cinnamon',
  'ground cloves',
  'ground coriander',
  'ground cumin',
  'ground fennel',
  'ground flaxseed',
  'ground ginger',
  'ground lamb',
  'ground mustard',
  'ground nutmeg',
  'ground paprika',
  'ground pepper',
  'ground red pepper',
  'ground sumac',
  'ground tumeric',
  'ground turkey',
  'ground turmeric',
  'ground white pepper',
  'guajillo chiles',
  'half & half',
  'halibut fillets',
  'hand cheese',
  'hard-boiled egg',
  'hare',
  'haricots verts',
  'harissa',
  'heavy cream',
  'heavy whipping cream',
  'herbs',
  'hing (powder)',
  'homemade chicken stock',
  'honey',
  'hot chili',
  'hot chili powder',
  'hot curry powder',
  'hot pepper',
  'hot pepper sauce',
  'hot sauce',
  'hot smoked paprika',
  'hot water',
  'hothouse cucumber',
  'hungarian paprika',
  'iceberg lettuce',
  'idaho potatoes',
  'indian saffron',
  'iodized salt',
  'jaggery',
  'jalapeno chilies',
  'jasmine rice',
  'jeera',
  'juice',
  'kabuli channa',
  'kaffir lime leaves',
  'kala jeera',
  'kale',
  'kale leaves',
  'kashmiri chile',
  'kasuri methi',
  'keema',
  'ketchup',
  'kewra',
  'kewra essence',
  'kewra water',
  'kidney beans',
  'king prawns',
  'kitchen king masala',
  'korma paste',
  'kosher salt',
  'lamb',
  'lamb cutlet',
  'lamb leg',
  'lamb neck fillets',
  'lamb rib chops',
  'lamb shanks',
  'lamb shoulder',
  'lamb stew meat',
  'lambs liver',
  'large carrots',
  'large eggs',
  'large garlic cloves',
  'large potatoes',
  'large shrimp',
  'large tomato',
  'lean minced lamb',
  'leaves',
  'leeks',
  'leg of lamb',
  'lemon',
  'lemon grass',
  'lemon juice',
  'lemon pepper',
  'lemon slices',
  'lemon wedges',
  'lemon zest',
  'lemongrass',
  'lentils',
  'less sodium beef broth',
  'light brown sugar',
  'light coconut milk',
  'light cream',
  'lime',
  'lime juice',
  'lime leaves',
  'lime wedges',
  'liver',
  'loin',
  'long grain white rice',
  'long pepper',
  'long-grain rice',
  'low fat mozzarella',
  'low salt chicken broth',
  'low sodium chicken broth',
  'low sodium soy sauce',
  'low sodium vegetable broth',
  'low-fat coconut milk',
  'low-fat greek yogurt',
  'low-fat plain yogurt',
  'low-fat yogurt',
  'mace',
  'malt vinegar',
  'mango',
  'mango chutney',
  'mango ginger',
  'maple syrup',
  'margarine',
  'marinade',
  'marinara sauce',
  'marrow',
  'marsala wine',
  'masala',
  'mashed potatoes',
  'masoor dal',
  'matki',
  'mayonnaise',
  'meat',
  'meat bones',
  'meat tenderizer',
  'medium carrot',
  'medium curry powder',
  'medium potatoes',
  'medium shrimp',
  'medium tomatoes',
  'medium zucchini',
  'melted butter',
  'methi',
  'methi leaves',
  'mild curry paste',
  'mild curry powder',
  'mild green chiles',
  'mild olive oil',
  'milk',
  'millet',
  'min',
  'minced chicken',
  'minced garlic',
  'minced ginger',
  'minced meat',
  'minced onion',
  'minced pork',
  'mint',
  'mint leaves',
  'mixed spice',
  'mixed vegetables',
  'moong dal',
  'mozzarella cheese',
  'mung beans',
  'muscovado sugar',
  'mushrooms',
  'mussels',
  'mustard',
  'mustard greens',
  'mustard oil',
  'mustard powder',
  'mustard seeds',
  'mutton',
  'naan',
  'natural peanut butter',
  'natural yogurt',
  'navy beans',
  'neutral oil',
  'new potatoes',
  'nigella seeds',
  'no salt added canned tomatoes',
  'no-salt-added diced tomatoes',
  'non dairy yogurt',
  'non-dairy milk',
  'nonfat greek yogurt',
  'nonfat plain greek yogurt',
  'nonfat yogurt plain',
  'nutmeg',
  'nutritional yeast',
  'nutritional yeast flakes',
  'nuts',
  'oil',
  'okra',
  'olive oil',
  'olives',
  'onion powder',
  'onion purée',
  'onion rings',
  'onion soup mix',
  'onion tops',
  'onions',
  'orange',
  'orange bell pepper',
  'orange food coloring',
  'organic chicken',
  'organic coconut oil',
  'palm sugar',
  'palm vinegar',
  'paneer',
  'paneer cheese',
  'panko breadcrumbs',
  'papadums',
  'paprika',
  'parsley',
  'parsley leaves',
  'peaches',
  'peanut butter',
  'peanut oil',
  'peanuts',
  'pearl onions',
  'peas',
  'peeled deveined shrimp',
  'peeled fresh ginger',
  'peeled shrimp',
  'pepper',
  'pepper flakes',
  'peppercorns',
  'petits pois',
  'phyllo pastry',
  'pickles',
  'pigeon breasts',
  'pigeon peas',
  'pimentos',
  'pineapple',
  'pinto beans',
  'pistachios',
  'pitted dates',
  'pizza doughs',
  'plain flour',
  'plain greek yogurt',
  'plain low fat greek yogurt',
  'plain soy yogurt',
  'plain whole-milk yogurt',
  'plain yogurt',
  'plum tomatoes',
  'plums',
  'pomegranate seeds',
  'poppadoms',
  'poppy seeds',
  'pork',
  'pork shoulder',
  'pork strips',
  'potato sticks',
  'potatoes',
  'powdered garlic',
  'powdered turmeric',
  'prawns',
  'pressed tofu',
  'pumpkin',
  'pumpkin purée',
  'quick cooking brown rice',
  'quinoa',
  'rack of lamb',
  'radishes',
  'raisins',
  'rajma',
  'rapeseed oil',
  'rasam powder',
  'raw cashews',
  'raw honey',
  'raw sugar',
  'red',
  'red bell pepper',
  'red chile powder',
  'red chili peppers',
  'red chili powder',
  'red curry paste',
  'red food coloring',
  'red kidney beans',
  'red lentils',
  'red onion',
  'red pepper',
  'red pepper flakes',
  'red potato',
  'red quinoa',
  'reduced fat coconut milk',
  'reduced sodium vegetable broth',
  'reduced-fat sour cream',
  'rice',
  'rice bran',
  'rice flour',
  'rice vinegar',
  'roast',
  'roasted cashews',
  'roasted ground cumin',
  'roasted peanuts',
  'roasted red peppers, drained',
  'roasted tomatoes',
  'rock salt',
  'rogan josh seasoning',
  'roma tomatoes',
  'root vegetables',
  'rose petals',
  'rose water',
  'roti',
  'rump steak',
  'russet potatoes',
  'safflower oil',
  'saffron',
  'saffron threads',
  'salad',
  'salmon',
  'salmon fillets',
  'salsa',
  'salt',
  'salt and ground black pepper',
  'salted butter',
  'sambal ulek',
  'sambhar powder',
  'sardines',
  'sauce',
  'scallions',
  'scotch bonnet chile',
  'sea salt',
  'seabass fillets',
  'seasoning',
  'seedless watermelon',
  'seeds',
  'semolina',
  'serrano',
  'serrano chiles',
  'serrano chilies',
  'serrano peppers',
  'sesame oil',
  'sesame seeds',
  'shahi jeera',
  'shallots',
  'shell-on shrimp',
  'shredded cabbage',
  'shredded carrots',
  'shredded coconut',
  'shrimp',
  'shrimp paste',
  'silken tofu',
  'skim milk',
  'skinless chicken breasts',
  'skinless chicken pieces',
  'skinless chicken thighs',
  'sliced almonds',
  'sliced carrots',
  'sliced green onions',
  'slivered almonds',
  'small green chile',
  'small new potatoes',
  'small onion',
  'small potatoes',
  'small tomatoes',
  'small yellow onion',
  'smoked paprika',
  'soft tofu',
  'sorghum',
  'soup',
  'sour cream',
  'soy milk',
  'soy sauce',
  'soy yogurt',
  'soya chunks',
  'spanish onion',
  'spanish paprika',
  'spices',
  'spinach',
  'spinach leaves',
  'split peas',
  'spring onions',
  'squash',
  'squid',
  'sriracha sauce',
  'star anise',
  'steamed rice',
  'steamed white rice',
  'stewed tomatoes',
  'stewing beef',
  'stock',
  'store bought low sodium chicken broth',
  'sugar',
  'sugar pumpkin',
  'sultana',
  'summer squash',
  'sun-dried tomatoes',
  'sun-dried tomatoes in oil',
  'sunflower oil',
  'sweet corn',
  'sweet onion',
  'sweet paprika',
  'sweet peas',
  'sweet potatoes',
  'sweetener',
  'swiss chard',
  'table salt',
  'tahini',
  'tamarind',
  'tamarind concentrate',
  'tamarind extract',
  'tamarind juice',
  'tamarind paste',
  'tamarind pulp',
  'tamarind purée',
  'tamarind water',
  'tandoori masala mix',
  'tandoori paste',
  'tandoori seasoning',
  'tandoori spices',
  'tea bags',
  'teas',
  'tempeh',
  'thai chile',
  'thyme',
  'tikka masala curry paste',
  'tilapia fillets',
  'toasted almonds',
  'toasted cashews',
  'toasted coconut',
  'toasted sesame seeds',
  'toasted slivered almonds',
  'toasted unsweetened coconut',
  'tofu',
  'tofu sour cream',
  'tomato ketchup',
  'tomato passata',
  'tomato paste',
  'tomato purée',
  'tomato sauce',
  'tomatoes',
  'tomatoes with juice',
  'toor dal',
  'tortillas',
  'tuna',
  'turkey',
  'turkey mince',
  'turmeric',
  'unsalted almonds',
  'unsalted butter',
  'unsalted cashews',
  'unsalted chicken stock',
  'unsalted roasted peanuts',
  'unsweetened coconut milk',
  'unsweetened shredded dried coconut',
  'unsweetened soymilk',
  'urad dal',
  'vanilla',
  'vegan butter',
  'vegan sour cream',
  'vegan yogurt',
  'vegetable base',
  'vegetable broth',
  'vegetable oil',
  'vegetable stock',
  'vegetable stock powder',
  'vegetables',
  'veggies',
  'vinegar',
  'virgin coconut oil',
  'virgin olive oil',
  'warm water',
  'water',
  'watermelon',
  'waxy potatoes',
  'wheat flour',
  'whipping cream',
  'white button mushrooms',
  'white flour',
  'white onion',
  'white pepper',
  'white poppy seeds',
  'white rice',
  'white vinegar',
  'white wine',
  'white wine vinegar',
  'whitefish',
  'whitefish fillets',
  'whiting fillets',
  'whole chicken',
  'whole cloves',
  'whole garam masala',
  'whole milk',
  'whole milk greek yogurt',
  'whole milk yoghurt',
  'whole peeled tomatoes',
  'whole wheat flour',
  'whole wheat pizza dough',
  'whole wheat tortillas',
  'wine vinegar',
  'winter squash',
  'xanthan gum',
  'yams',
  'yardlong beans',
  'yellow curry paste',
  'yellow food coloring',
  'yellow lentils',
  'yellow mustard seeds',
  'yellow onion',
  'yellow peppers',
  'yellow split peas',
  'yogurt',
  'yoplait',
  'yukon gold potatoes',
  'zucchini',
];
